#pragma once
#include <ESPmDNS.h>
#include <ArduinoOTA.h>
#include <Wire.h>
#include <WiFi.h>
#include <LittleFS.h>
#include <SparkFun_u-blox_GNSS_v3.h>
#include <sfe_bus.h>
#include <u-blox_Class_and_ID.h>
#include <u-blox_GNSS.h>
#include <u-blox_config_keys.h>
#include <u-blox_external_typedefs.h>
#include <u-blox_structs.h>
#include <LSM6DSV16XSensor.h>
#include <RadioLib.h>
#include <core/core_pins.hpp>
#include <core/core_timing.hpp>
#include <core/core_vectors.hpp>
#include <core/core_constants.hpp>
#include <core/core_keywords.hpp>
#include <core/core_packing.hpp>